version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/my-web-app ./
artifacts:
  files:
    - my-web-app/**/*
  discard-paths: yes
