version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mkdir -p /codebuild/output/src153386732/src/target/deploy
      - cp -R target/petclinic.war /src/src/main/webapp/ 
     
artifacts:
  files:
      - webapp/**/*
