version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mkdir artifact    <-- create folder to extract war file content
      - unzip target/petclinic.war -d artifact/    <-- unzip to that folder
artifacts:
  files:
    - artifact/**/*   <-- reference all those files as the artifact
    name: artifact
  cache:
    paths:
        - '/root/.m2/**/*'
