version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mkdir -p /codebuild/output/src153386732/src/target/deploy
      - mv target/petclinic.war deploy 
     
artifacts:
  files:
      - petclinic.war 
      - .ebextensions/**/*
